In [14]:
import pandas as pd
import numpy as np


df = pd.DataFrame({
    'A': [1, 2, np.nan, 4, np.nan, 6, 7,21],
    'B': [np.nan, 2, np.nan, 4, 5, 6, 7,np.nan],
    'C': ['apple', 'banana', 'apple', 'orange', 'banana', np.nan, 'apple','apple'],
    'D': [np.nan, np.nan, np.nan, 'keep', 'drop', 'keep', 'drop',np.nan],
    'E': [None, 1, 2, 3, None, 5, 6,None],
    'F': ['  spaced  ', 'trim  ', 'trim', '  spaced  ', np.nan, 'clean', 'clean','  spaced  '],
    'G': ['Male', 'Female', 'Female', 'Male', 'Male', np.nan, 'Other','Male'],
    'H': [1, 1, 2, 2, 3, 3, 3,1],
    'I': [10, 10, 20, 20, 30, 30, 30,10]
})

df

      A    B       C     D    E           F       G  H   I
0   1.0  NaN   apple   NaN  NaN    spaced      Male  1  10
1   2.0  2.0  banana   NaN  1.0      trim    Female  1  10
2   NaN  NaN   apple   NaN  2.0        trim  Female  2  20
3   4.0  4.0  orange  keep  3.0    spaced      Male  2  20
4   NaN  5.0  banana  drop  NaN         NaN    Male  3  30
5   6.0  6.0     NaN  keep  5.0       clean     NaN  3  30
6   7.0  7.0   apple  drop  6.0       clean   Other  3  30
7  21.0  NaN   apple   NaN  NaN    spaced      Male  1  10

## 1. Handling Missing Data Using dropna()
    a) Drop Rows with Any Missing Value

        how=’any’: Drop if any value is missing (default)

        and axis=0: Drop rows

In [15]:
# Drop rows with any NaN
df1=df.dropna(axis=0,how="any") # these are the default values if you use dropna without any parameters

df1

     A    B       C     D    E           F      G  H   I
3  4.0  4.0  orange  keep  3.0    spaced     Male  2  20
6  7.0  7.0   apple  drop  6.0       clean  Other  3  30

## b) Drop Columns Where All Values Are NaN

In [16]:
# Drop columns where all values are NaN
df['J']=[np.nan,np.nan,np.nan,np.nan,np.nan,np.nan,np.nan,np.nan]
df

      A    B       C     D    E           F       G  H   I   J
0   1.0  NaN   apple   NaN  NaN    spaced      Male  1  10 NaN
1   2.0  2.0  banana   NaN  1.0      trim    Female  1  10 NaN
2   NaN  NaN   apple   NaN  2.0        trim  Female  2  20 NaN
3   4.0  4.0  orange  keep  3.0    spaced      Male  2  20 NaN
4   NaN  5.0  banana  drop  NaN         NaN    Male  3  30 NaN
5   6.0  6.0     NaN  keep  5.0       clean     NaN  3  30 NaN
6   7.0  7.0   apple  drop  6.0       clean   Other  3  30 NaN
7  21.0  NaN   apple   NaN  NaN    spaced      Male  1  10 NaN

If a column is completely useless—i.e., all values are missing—then setting a rid of it.

In [19]:
df=df.dropna(axis=1,how="all")
df

      A    B       C     D    E           F       G  H   I
0   1.0  NaN   apple   NaN  NaN    spaced      Male  1  10
1   2.0  2.0  banana   NaN  1.0      trim    Female  1  10
2   NaN  NaN   apple   NaN  2.0        trim  Female  2  20
3   4.0  4.0  orange  keep  3.0    spaced      Male  2  20
4   NaN  5.0  banana  drop  NaN         NaN    Male  3  30
5   6.0  6.0     NaN  keep  5.0       clean     NaN  3  30
6   7.0  7.0   apple  drop  6.0       clean   Other  3  30
7  21.0  NaN   apple   NaN  NaN    spaced      Male  1  10

how=’all’: Drop if all values are missing

and axis=1: Drop columns

## c) Drop Rows Based on Specific Columns

In [21]:
# Keep columns with at least 5 non-NaN
df4=df.dropna(thresh=5,axis=1)
df4

      A    B       C    E           F       G  H   I
0   1.0  NaN   apple  NaN    spaced      Male  1  10
1   2.0  2.0  banana  1.0      trim    Female  1  10
2   NaN  NaN   apple  2.0        trim  Female  2  20
3   4.0  4.0  orange  3.0    spaced      Male  2  20
4   NaN  5.0  banana  NaN         NaN    Male  3  30
5   6.0  6.0     NaN  5.0       clean     NaN  3  30
6   7.0  7.0   apple  6.0       clean   Other  3  30
7  21.0  NaN   apple  NaN    spaced      Male  1  10

In [22]:
df

      A    B       C     D    E           F       G  H   I
0   1.0  NaN   apple   NaN  NaN    spaced      Male  1  10
1   2.0  2.0  banana   NaN  1.0      trim    Female  1  10
2   NaN  NaN   apple   NaN  2.0        trim  Female  2  20
3   4.0  4.0  orange  keep  3.0    spaced      Male  2  20
4   NaN  5.0  banana  drop  NaN         NaN    Male  3  30
5   6.0  6.0     NaN  keep  5.0       clean     NaN  3  30
6   7.0  7.0   apple  drop  6.0       clean   Other  3  30
7  21.0  NaN   apple   NaN  NaN    spaced      Male  1  10

## d) Fill All Missing Values with a Single Value

In [23]:
# Only consider columns A and B
df5=df.dropna(subset=['A', 'B'])

df5

     A    B       C     D    E           F       G  H   I
1  2.0  2.0  banana   NaN  1.0      trim    Female  1  10
3  4.0  4.0  orange  keep  3.0    spaced      Male  2  20
5  6.0  6.0     NaN  keep  5.0       clean     NaN  3  30
6  7.0  7.0   apple  drop  6.0       clean   Other  3  30

# 2. Handling Missing Data Using fillna()
## a) Fill All Missing Values with a Single Value